"""Bilingual text resources for the Streamlit interface."""

from __future__ import annotations


UI_TEXT: dict[str, dict[str, str]] = {
    "en": {
        "language_label": "Language",
        "hero_title": "Political Spectrum Analyzer",
        "hero_subtitle": "Build, compare, and interpret political profiles from 16 ideological scores. Enter one or several profiles, project them on the spectrum, compare them with reference personalities, and get a detailed score-based reading of each profile.",
        "hero_help": "Start by entering a profile manually, importing copied Politiscales-style results, or loading a saved profile JSON. The app then shows the graph position, closest references, and a personalized analysis based on the strongest and weakest axes.",
        "politiscales_title": "Need to take or retake the test?",
        "politiscales_description": "You can open Politiscales in a new browser tab, take the test there, then copy and paste the results into this app.",
        "politiscales_link_label": "Open Politiscales test",
        "tab_input": "Input",
        "tab_guide": "Guide",
        "tab_visualization": "Visualization",
        "tab_reference": "Reference data",
        "tab_methodology": "Methodology",
        "active_tab_label": "Active tab",
        "active_tab_help": "Streamlit reruns the script after every widget change. This selector keeps inactive tabs from loading reference data or building charts.",
        "inactive_tab_notice": "Select {view_label} in the sidebar Active tab selector to load this tab.",
        "sidebar_controls": "Controls",
        "score_input_mode_header": "Score input mode",
        "score_input_mode_caption": "Choose slider-based manual scoring or precise numeric fields before editing profile scores.",
        "reference_dataset_not_loaded": "Reference dataset is not loaded on this tab.",
        "export_options": "Export options",
        "csv_export_mode": "CSV export mode",
        "export_profiles_only": "Profiles only",
        "export_closest_references": "Profiles + closest references",
        "export_all_references": "Profiles + all references",
        "export_filtered_references": "Profiles + current filtered references",
        "closest_references_count": "Closest references count",
        "political_positioning_header": "Political positioning",
        "reference_dataset_header": "Reference dataset",
        "download_analysis_csv": "Download analysis CSV",
        "guide_header": "User guide",
        "guide_intro": "Use this workflow to create, compare, save, and export political profiles. Start with one profile, then add more profiles if you want to compare several people or scenarios.",
        "guide_step_1": "Step 1 - Enter scores",
        "guide_step_1_body": "Choose the number of profiles to compare. For each profile, you can type exact values with Manual numeric entry, disable it and use sliders, or paste copied Politiscales-style text and apply detected scores.",
        "guide_step_2": "Step 2 - Read the graph",
        "guide_step_2_body": "Open the Visualization tab to view the profile position, closest reference personalities, detailed profile reading, and axis-by-axis balance.",
        "guide_step_3": "Step 3 - Save or export",
        "guide_step_3_body": "Save each profile individually as JSON, or export the full analysis as CSV for Excel, Power BI, or later comparison.",
        "recommended_workflow": "Recommended workflow",
        "recommended_workflow_body": "- Keep Manual numeric entry enabled for precise values.\\n- Enter one profile first and check the result.\\n- Save that profile as JSON if you want to reuse it later.\\n- Increase the number of profiles if you want comparison.\\n- Use filters only when you want reference personalities visible.\\n- Export the CSV when you want a structured analysis file.",
        "profile_save_import": "Profile save and import",
        "profile_save_import_body": "Profile saving is currently file-based. Each profile can be downloaded as a JSON file and imported again later into any profile form. Once imported, the profile remains editable.",
        "input_mode": "Input mode",
        "input_mode_body": "Manual numeric entry is enabled by default. Keep it enabled when you want exact score values. Disable it when you prefer visual adjustment with sliders.",
        "reference_filters": "Reference filters",
        "reference_filters_body": "Reference personalities are hidden by default. None hides references for a cleaner graph. Any displays references for that filter dimension. A specific value displays only matching references.",
        "reference_filters_sidebar": "Reference filters",
        "reference_filters_hidden_caption": "Reference profiles stay hidden until at least one filter is selected. Select Any to keep all values for a filter.",
        "filter_countries": "Countries",
        "filter_ideology_families": "Ideology families",
        "filter_role_categories": "Role categories",
        "filter_gender": "Gender",
        "filter_centuries": "Centuries",
        "filter_confidence": "Confidence",
        "filter_help_generic": "Select one or several values. Any disables this filter. None matches missing values.",
        "filter_help_gender": "Optional metadata filter. Gender never affects scoring or ideological interpretation.",
        "reference_displayed_count": "{shown} / {total} reference profiles displayed.",
        "reference_match_count": "{shown} / {total} reference profiles match the current filters.",
        "methodology_header": "How the analyzer works",
        "methodology_intro": "The analyzer turns 16 ideological scores into a readable political position. Each score contributes to one or more interpretive blocks. Those blocks are then compared to produce the final economic coordinate x and societal coordinate y.",
        "coordinate_system": "1. Coordinate system",
        "score_blocks": "2. Score blocks and coefficients",
        "raw_axis": "3. Raw axis calculation",
        "secondary_adjustments": "4. Secondary adjustments",
        "normalization": "5. Normalization and final coordinates",
        "axes_meaning": "6. Meaning of the 16 axes",
        "read_result": "7. How to read your result",
        "input_header": "Profile input",
        "input_intro": "Add one or several profiles. Choose slider input or exact numeric input from the sidebar. Each profile can be saved and imported independently.",
        "manual_numeric_entry": "Manual numeric entry",
        "manual_numeric_help": "On: type exact values for each axis. Off: adjust scores with sliders.",
        "profile_count_label": "Number of profiles to compare",
        "profile_count_help": "Use up to 8 profiles to keep the chart readable.",
        "import_saved_profile": "Import a saved profile",
        "select_saved_json": "Select a saved profile JSON",
        "load_this_profile": "Load this profile",
        "save_this_profile": "Save this profile",
        "download_profile_json": "Download this profile JSON",
        "copied_text_import": "Import from copied Politiscales-style text",
        "paste_results_text": "Paste copied results text",
        "apply_copied_scores": "Apply copied-text scores to this profile",
        "profile_loaded": "Profile loaded. The fields have been filled and remain editable.",
        "profile_save_caption": "Profile save/import is currently local and file-based. A future authenticated version can store profiles per user account.",
        "profile_heading": "Profile {number}",
        "copied_scores_detected": "{count}/16 non-zero scores detected from copied text.",
        "analysis_no_profile": "No profile available for analysis.",
        "analysis_single_header": "Analysis - {name}",
        "analysis_multi_header": "Multi-profile analysis",
        "analysis_details_by_profile": "Details by profile",
        "analysis_personalized_reading": "Personalized profile reading",
        "analysis_detailed_notes": "Detailed reading notes",
        "analysis_highlights": "Profile highlights",
        "analysis_dominant_axes": "Dominant axes",
        "analysis_weakest_axes": "Weakest axes",
        "analysis_axis_balance": "Axis-by-axis balance",
        "analysis_score_by_score": "Score-by-score reading",
        "analysis_economic_reading": "Economic reading",
        "analysis_societal_reading": "Societal reading",
        "analysis_strategic_reading": "Strategic reading",
        "analysis_internal_tension": "Internal tension",
        "metric_x_coordinate": "x coordinate",
        "metric_y_coordinate": "y coordinate",
        "metric_quadrant": "Quadrant",
        "metric_distance_to_center": "Distance to center",
        "table_rank": "Rank",
        "table_name": "Name",
        "table_group": "Group",
        "table_country": "Country",
        "table_period": "Period",
        "table_ideology_family": "Ideology family",
        "table_role_category": "Role category",
        "table_gender": "Gender",
        "table_country_codes": "Country codes",
        "table_century": "Century",
        "table_confidence": "Confidence",
        "table_notes": "Notes",
        "table_distance": "Distance",
        "table_axis": "Axis",
        "table_score": "Score",
        "table_level": "Level",
        "table_meaning": "Meaning",
        "table_dimension": "Dimension",
        "table_first_pole": "First pole",
        "table_first_score": "First score",
        "table_second_pole": "Second pole",
        "table_second_score": "Second score",
        "table_leading_tendency": "Leading tendency",
        "table_reading": "Reading",
        "table_profile": "Profile",
        "table_profile_type": "Profile type",
        "table_closest_reference": "Closest reference",
        "profile_comparison_header": "Profile comparison analysis",
        "profile_comparison_intro": "This section compares profiles pair by pair using their map distance and their raw 16-axis scores.",
        "profile_comparison_not_enough": "Add at least two profiles to generate a comparison analysis.",
        "profile_comparison_summary": "Summary",
        "profile_comparison_table": "Comparison table",
        "profile_comparison_shared_dominant": "Shared dominant axes: {axes}",
        "profile_comparison_shared_weak": "Shared weak axes: {axes}",
        "tab_about": "About / How to use",
        "about_header": "About this analyzer",
        "about_intro": "Political Spectrum Analyzer is an interactive tool for turning political test scores into a readable profile, a graph position, and a comparison against reference personalities.",
        "about_for_users_title": "What you can do here",
        "about_for_users_body": "- Create one or several political profiles.\\n- Compare profiles on the same graph.\\n- Save and import profiles as JSON.\\n- Export structured results as CSV.\\n- Read a detailed interpretation based on the strongest and weakest axes.",
        "about_how_to_use_title": "How to use it",
        "about_how_to_use_body": "- Choose a language.\\n- Enter scores manually, use sliders, or paste copied Politiscales-style results.\\n- Add more profiles if you want comparison.\\n- Open the visualization tab to read the graph and the detailed analysis.\\n- Use filters only when you want to display reference personalities.\\n- Save individual profiles as JSON if you want to reuse them later.",
        "about_score_title": "How to read the result",
        "about_score_body": "The x-axis represents the economic position. The y-axis represents the societal position. The detailed interpretation uses the full 16-axis score set, so it gives more context than the graph alone.",
        "about_privacy_title": "Data and privacy",
        "about_privacy_body": "The app does not require an account. Profile saving is file-based: when you download a JSON profile, it stays on your device. The current web version does not store personal profiles in a database.",
        "about_desktop_title": "Desktop and web versions",
        "about_desktop_body": "The desktop version includes optional OCR for local screenshots. The Streamlit web version is lighter and uses copied-text import instead, which makes online deployment more reliable.",
        "advanced_interpretation_header": "Advanced profile interpretation",
        "advanced_interpretation_intro": "This analysis uses the scoring model v2 secondary dimensions to explain the profile beyond its x/y position.",
        "advanced_interpretation_dominant": "Dominant axes",
        "advanced_interpretation_weak": "Weak axes",
        "advanced_interpretation_secondary": "Secondary dimensions",
        "advanced_interpretation_table": "Advanced interpretation table",
        "advanced_comparison_header": "Advanced profile comparison",
        "advanced_comparison_intro": "This comparison uses graph distance, economic similarity, societal similarity and secondary dimensions from the full 16-axis profile.",
        "advanced_comparison_not_enough": "Add at least two profiles to generate advanced comparison.",
        "advanced_comparison_matrix": "Similarity matrix",
        "advanced_comparison_table": "Advanced comparison table",
        "advanced_comparison_gaps": "Largest axis and secondary-dimension gaps",
        "formula_main_blocks_intro": "The analyzer does not use a black-box model. It builds four weighted blocks, then compares them.",
        "formula_coefficients_note": "A coefficient is a weight. The higher it is, the more that score influences the final coordinate. The current v3 model keeps ecology, productivism, nationalism, and internationalism below the core economic and social-authority markers.",
        "formula_left_block_title": "Economic-left block",
        "formula_left_block_explanation": "- 0.95 * communisme: strongest economic-left marker; it directly pushes x to the left.\\n- 0.75 * regulation: strong interventionist marker; it pushes x to the left.\\n- 0.28 * ecologie: secondary contribution because ecology can also appear in conservative, localist, or technocratic profiles.\\n- revolution excluded from coordinate blocks: political change strategy, not an economic doctrine.",
        "formula_right_block_title": "Economic-right block",
        "formula_right_block_explanation": "- 0.95 * capitalisme: strongest economic-right marker; it directly pushes x to the right.\\n- 0.80 * laissez_faire: strong market-autonomy marker; it pushes x to the right.\\n- 0.24 * productivisme: secondary contribution because growth and production can exist in several systems.\\n- reformisme excluded from coordinate blocks: political change strategy, not an economic doctrine.",
        "formula_libertarian_block_title": "Libertarian / progressive social block",
        "formula_libertarian_block_explanation": "- 0.75 * constructivisme: strong progressive-social marker because it reflects flexible social interpretation.\\n- 0.70 * justice_rehabilitative: strong anti-punitive marker because it favors reintegration and prevention.\\n- 0.75 * progressisme: strong social-change marker.\\n- 0.35 * internationalisme: moderate openness marker because it can also describe institutional or technocratic politics.",
        "formula_authoritarian_block_title": "Authoritarian / conservative social block",
        "formula_authoritarian_block_explanation": "- 0.60 * essentialisme: conservative-social marker because it reflects fixed social categories.\\n- 0.70 * justice_punitive: strong authority marker because it emphasizes sanction and deterrence.\\n- 0.70 * conservatisme: strong continuity and stability marker.\\n- 0.30 * nationalisme: moderate sovereignty marker, kept below the core authority axes.",
        "formula_raw_axis_explanation": "The model subtracts opposite blocks. right_economic - left_economic gives the x direction. authoritarian_social - libertarian_social gives the y direction.",
        "formula_adjustments_explanation": "- productivisme - ecologie weakly refines the growth-versus-ecological-constraint reading.\\n- nationalisme - internationalisme weakly refines the sovereignty-versus-global-openness reading.\\n- revolution and reformisme are used for detailed strategic interpretation, not direct x/y positioning.",
        "formula_normalization_explanation": "The raw scores are normalized with tanh. Strong profiles move toward the edges, but the chart remains readable.",
    },
    "fr": {
        "language_label": "Langue",
        "hero_title": "Political Spectrum Analyzer",
        "hero_subtitle": "Creez, comparez et interpretez des profils politiques a partir de 16 scores ideologiques. Ajoutez un ou plusieurs profils, projetez-les sur le spectre, comparez-les a des personnalites de reference et obtenez une analyse detaillee de chaque profil.",
        "hero_help": "Commencez par saisir un profil manuellement, importer un texte copie depuis Politiscales, ou charger un profil JSON sauvegarde. L'application affiche ensuite la position sur le graphe, les references les plus proches et une analyse personnalisee des axes dominants et faibles.",
        "politiscales_title": "Besoin de faire ou refaire le test ?",
        "politiscales_description": "Vous pouvez ouvrir Politiscales dans un nouvel onglet, faire le test, puis copier-coller les resultats dans cette application.",
        "politiscales_link_label": "Ouvrir le test Politiscales",
        "tab_input": "Saisie",
        "tab_guide": "Guide",
        "tab_visualization": "Visualisation",
        "tab_reference": "Donnees de reference",
        "tab_methodology": "Methodologie",
        "active_tab_label": "Onglet actif",
        "active_tab_help": "Streamlit relance le script apres chaque changement de widget. Ce selecteur evite aux onglets inactifs de charger les donnees de reference ou de construire les graphiques.",
        "inactive_tab_notice": "Selectionnez {view_label} dans le selecteur Onglet actif de la barre laterale pour charger cet onglet.",
        "sidebar_controls": "Controles",
        "score_input_mode_header": "Mode de saisie des scores",
        "score_input_mode_caption": "Choisissez les sliders ou les champs numeriques precis avant de modifier les scores du profil.",
        "reference_dataset_not_loaded": "Le dataset de reference n'est pas charge sur cet onglet.",
        "export_options": "Options d'export",
        "csv_export_mode": "Mode d'export CSV",
        "export_profiles_only": "Profils uniquement",
        "export_closest_references": "Profils + references les plus proches",
        "export_all_references": "Profils + toutes les references",
        "export_filtered_references": "Profils + references filtrees",
        "closest_references_count": "Nombre de references les plus proches",
        "political_positioning_header": "Positionnement politique",
        "reference_dataset_header": "Dataset de reference",
        "download_analysis_csv": "Telecharger l'analyse CSV",
        "guide_header": "Guide utilisateur",
        "guide_intro": "Utilisez ce parcours pour creer, comparer, sauvegarder et exporter des profils politiques. Commencez avec un seul profil, puis ajoutez-en plusieurs si vous voulez comparer des personnes ou des scenarios.",
        "guide_step_1": "Etape 1 - Saisir les scores",
        "guide_step_1_body": "Choisissez le nombre de profils a comparer. Pour chaque profil, vous pouvez saisir les valeurs exactes, desactiver la saisie numerique pour utiliser les sliders, ou coller un texte Politiscales et appliquer les scores detectes.",
        "guide_step_2": "Etape 2 - Lire le graphe",
        "guide_step_2_body": "Ouvrez l'onglet Visualisation pour voir la position du profil, les references les plus proches, l'analyse detaillee et l'equilibre axe par axe.",
        "guide_step_3": "Etape 3 - Sauvegarder ou exporter",
        "guide_step_3_body": "Sauvegardez chaque profil individuellement en JSON, ou exportez l'analyse complete en CSV pour Excel, Power BI ou une comparaison ulterieure.",
        "recommended_workflow": "Parcours recommande",
        "recommended_workflow_body": "- Gardez la saisie numerique activee pour des valeurs precises.\\n- Saisissez d'abord un profil et verifiez le resultat.\\n- Sauvegardez ce profil en JSON si vous voulez le reutiliser.\\n- Augmentez le nombre de profils si vous voulez comparer.\\n- Utilisez les filtres uniquement si vous voulez afficher les personnalites de reference.\\n- Exportez le CSV lorsque vous voulez un fichier d'analyse structure.",
        "profile_save_import": "Sauvegarde et import de profil",
        "profile_save_import_body": "La sauvegarde est actuellement locale et basee sur des fichiers. Chaque profil peut etre telecharge en JSON puis importe plus tard dans n'importe quel formulaire. Une fois importe, le profil reste modifiable.",
        "input_mode": "Mode de saisie",
        "input_mode_body": "La saisie numerique manuelle est activee par defaut. Gardez-la activee pour saisir des valeurs exactes. Desactivez-la si vous preferez ajuster les scores avec des sliders.",
        "reference_filters": "Filtres de reference",
        "reference_filters_body": "Les personnalites de reference sont masquees par defaut. None masque les references pour garder un graphe lisible. Any affiche les references pour cette dimension. Une valeur precise affiche uniquement les references correspondantes.",
        "reference_filters_sidebar": "Filtres de reference",
        "reference_filters_hidden_caption": "Les profils de reference restent masques tant qu'aucun filtre n'est selectionne. Selectionnez Any pour conserver toutes les valeurs d'un filtre.",
        "filter_countries": "Pays",
        "filter_ideology_families": "Familles ideologiques",
        "filter_role_categories": "Categories de role",
        "filter_gender": "Genre",
        "filter_centuries": "Siecles",
        "filter_confidence": "Confiance",
        "filter_help_generic": "Selectionnez une ou plusieurs valeurs. Any desactive ce filtre. None correspond aux valeurs manquantes.",
        "filter_help_gender": "Filtre de metadonnees optionnel. Le genre n'affecte jamais le score ni l'interpretation ideologique.",
        "reference_displayed_count": "{shown} / {total} profils de reference affiches.",
        "reference_match_count": "{shown} / {total} profils de reference correspondent aux filtres actuels.",
        "methodology_header": "Comment fonctionne l'analyseur",
        "methodology_intro": "L'analyseur transforme 16 scores ideologiques en une position politique lisible. Chaque score contribue a un ou plusieurs blocs d'interpretation. Ces blocs sont ensuite compares pour produire la coordonnee economique x et la coordonnee societale y.",
        "coordinate_system": "1. Systeme de coordonnees",
        "score_blocks": "2. Blocs de scores et coefficients",
        "raw_axis": "3. Calcul brut des axes",
        "secondary_adjustments": "4. Ajustements secondaires",
        "normalization": "5. Normalisation et coordonnees finales",
        "axes_meaning": "6. Signification des 16 axes",
        "read_result": "7. Comment lire le resultat",
        "input_header": "Saisie du profil",
        "input_intro": "Ajoutez un ou plusieurs profils. Choisissez la saisie exacte ou les sliders depuis la barre laterale. Chaque profil peut etre sauvegarde et importe independamment.",
        "manual_numeric_entry": "Saisie numerique manuelle",
        "manual_numeric_help": "Activee : saisir les valeurs exactes. Desactivee : ajuster les scores avec des sliders.",
        "profile_count_label": "Nombre de profils a comparer",
        "profile_count_help": "Utilisez jusqu'a 8 profils pour garder le graphe lisible.",
        "import_saved_profile": "Importer un profil sauvegarde",
        "select_saved_json": "Selectionner un profil JSON sauvegarde",
        "load_this_profile": "Charger ce profil",
        "save_this_profile": "Sauvegarder ce profil",
        "download_profile_json": "Telecharger ce profil JSON",
        "copied_text_import": "Importer depuis un texte Politiscales copie",
        "paste_results_text": "Coller le texte des resultats",
        "apply_copied_scores": "Appliquer les scores detectes a ce profil",
        "profile_loaded": "Profil charge. Les champs ont ete remplis et restent modifiables.",
        "profile_save_caption": "La sauvegarde est actuellement locale et basee sur des fichiers. Une future version authentifiee pourra stocker les profils par compte utilisateur.",
        "profile_heading": "Profil {number}",
        "copied_scores_detected": "{count}/16 scores non nuls detectes depuis le texte copie.",
        "analysis_no_profile": "Aucun profil disponible pour l'analyse.",
        "analysis_single_header": "Analyse - {name}",
        "analysis_multi_header": "Analyse multi-profils",
        "analysis_details_by_profile": "Details par profil",
        "analysis_personalized_reading": "Lecture personnalisee du profil",
        "analysis_detailed_notes": "Notes de lecture detaillees",
        "analysis_highlights": "Points saillants du profil",
        "analysis_dominant_axes": "Axes dominants",
        "analysis_weakest_axes": "Axes les plus faibles",
        "analysis_axis_balance": "Equilibre axe par axe",
        "analysis_score_by_score": "Lecture score par score",
        "analysis_economic_reading": "Lecture economique",
        "analysis_societal_reading": "Lecture societale",
        "analysis_strategic_reading": "Lecture strategique",
        "analysis_internal_tension": "Tension interne",
        "metric_x_coordinate": "Coordonnee x",
        "metric_y_coordinate": "Coordonnee y",
        "metric_quadrant": "Quadrant",
        "metric_distance_to_center": "Distance au centre",
        "table_rank": "Rang",
        "table_name": "Nom",
        "table_group": "Groupe",
        "table_country": "Pays",
        "table_period": "Periode",
        "table_ideology_family": "Famille ideologique",
        "table_role_category": "Categorie de role",
        "table_gender": "Genre",
        "table_country_codes": "Codes pays",
        "table_century": "Siecle",
        "table_confidence": "Confiance",
        "table_notes": "Notes",
        "table_distance": "Distance",
        "table_axis": "Axe",
        "table_score": "Score",
        "table_level": "Niveau",
        "table_meaning": "Sens",
        "table_dimension": "Dimension",
        "table_first_pole": "Premier pole",
        "table_first_score": "Premier score",
        "table_second_pole": "Second pole",
        "table_second_score": "Second score",
        "table_leading_tendency": "Tendance dominante",
        "table_reading": "Lecture",
        "table_profile": "Profil",
        "table_profile_type": "Type de profil",
        "table_closest_reference": "Reference la plus proche",
        "profile_comparison_header": "Analyse comparative des profils",
        "profile_comparison_intro": "Cette section compare les profils deux a deux a partir de leur distance sur le graphe et de leurs 16 scores bruts.",
        "profile_comparison_not_enough": "Ajoutez au moins deux profils pour generer une analyse comparative.",
        "profile_comparison_summary": "Resume",
        "profile_comparison_table": "Tableau comparatif",
        "profile_comparison_shared_dominant": "Axes dominants partages : {axes}",
        "profile_comparison_shared_weak": "Axes faibles partages : {axes}",
        "tab_about": "A propos / Mode d emploi",
        "about_header": "A propos de cet analyseur",
        "about_intro": "Political Spectrum Analyzer est un outil interactif qui transforme des scores politiques en profil lisible, en position sur un graphe et en comparaison avec des personnalites de reference.",
        "about_for_users_title": "Ce que vous pouvez faire",
        "about_for_users_body": "- Creer un ou plusieurs profils politiques.\\n- Comparer plusieurs profils sur le meme graphe.\\n- Sauvegarder et importer des profils en JSON.\\n- Exporter les resultats en CSV.\\n- Lire une interpretation detaillee basee sur les axes les plus forts et les plus faibles.",
        "about_how_to_use_title": "Comment l utiliser",
        "about_how_to_use_body": "- Choisissez une langue.\\n- Entrez les scores manuellement, utilisez les sliders ou collez des resultats de type Politiscales.\\n- Ajoutez plusieurs profils si vous voulez comparer.\\n- Ouvrez l onglet Visualisation pour lire le graphe et l analyse detaillee.\\n- Utilisez les filtres uniquement si vous voulez afficher les personnalites de reference.\\n- Sauvegardez les profils individuellement en JSON si vous voulez les reutiliser.",
        "about_score_title": "Comment lire le resultat",
        "about_score_body": "L axe x represente la position economique. L axe y represente la position societale. L interpretation detaillee utilise les 16 scores, ce qui donne plus de contexte que le graphe seul.",
        "about_privacy_title": "Donnees et confidentialite",
        "about_privacy_body": "L application ne demande pas de compte. La sauvegarde est basee sur des fichiers : quand vous telechargez un profil JSON, il reste sur votre appareil. La version web actuelle ne stocke pas les profils personnels dans une base de donnees.",
        "about_desktop_title": "Versions desktop et web",
        "about_desktop_body": "La version desktop inclut un OCR optionnel pour les captures locales. La version web Streamlit est plus legere et utilise plutot l import par texte copie, ce qui rend le deploiement en ligne plus fiable.",
        "advanced_interpretation_header": "Interpretation avancee du profil",
        "advanced_interpretation_intro": "Cette analyse utilise les dimensions secondaires du profil complet a 16 axes pour expliquer le profil au-dela de sa position x/y.",
        "advanced_interpretation_dominant": "Axes dominants",
        "advanced_interpretation_weak": "Axes faibles",
        "advanced_interpretation_secondary": "Dimensions secondaires",
        "advanced_interpretation_table": "Tableau d interpretation avancee",
        "advanced_comparison_header": "Comparaison avancee des profils",
        "advanced_comparison_intro": "Cette comparaison utilise la distance sur le graphe, la similarite economique, la similarite societale et les dimensions secondaires du profil complet a 16 axes.",
        "advanced_comparison_not_enough": "Ajoutez au moins deux profils pour generer une comparaison avancee.",
        "advanced_comparison_matrix": "Matrice de similarite",
        "advanced_comparison_table": "Tableau de comparaison avancee",
        "advanced_comparison_gaps": "Principaux ecarts par axe et dimension secondaire",
        "formula_main_blocks_intro": "L'analyseur n'utilise pas un modele boite noire. Il construit quatre blocs ponderes, puis les compare.",
        "formula_coefficients_note": "Un coefficient est un poids. Plus il est eleve, plus le score influence la coordonnee finale. Le modele v3 actuel garde ecologie, productivisme, nationalisme et internationalisme sous les marqueurs economiques et societaux centraux.",
        "formula_left_block_title": "Bloc economique de gauche",
        "formula_left_block_explanation": "- 0.95 * communisme : marqueur economique de gauche le plus fort ; il pousse directement x vers la gauche.\\n- 0.75 * regulation : marqueur interventionniste fort ; il pousse x vers la gauche.\\n- 0.28 * ecologie : contribution secondaire car l'ecologie peut aussi apparaitre dans des profils conservateurs, localistes ou technocratiques.\\n- revolution excluded from coordinate blocks : strategie de changement politique, pas doctrine economique.",
        "formula_right_block_title": "Bloc economique de droite",
        "formula_right_block_explanation": "- 0.95 * capitalisme : marqueur economique de droite le plus fort ; il pousse directement x vers la droite.\\n- 0.80 * laissez_faire : marqueur fort d'autonomie du marche ; il pousse x vers la droite.\\n- 0.24 * productivisme : contribution secondaire car croissance et production peuvent exister dans plusieurs systemes.\\n- reformisme excluded from coordinate blocks : strategie de changement politique, pas doctrine economique.",
        "formula_libertarian_block_title": "Bloc societal libertaire / progressiste",
        "formula_libertarian_block_explanation": "- 0.75 * constructivisme : marqueur social progressiste fort car il traduit une lecture flexible du social.\\n- 0.70 * justice_rehabilitative : marqueur anti-punitif fort car il favorise reintegration et prevention.\\n- 0.75 * progressisme : marqueur fort d'ouverture au changement social.\\n- 0.35 * internationalisme : marqueur modere d'ouverture car il peut aussi decrire une politique institutionnelle ou technocratique.",
        "formula_authoritarian_block_title": "Bloc societal autoritaire / conservateur",
        "formula_authoritarian_block_explanation": "- 0.60 * essentialisme : marqueur social conservateur car il traduit des categories sociales plus fixes.\\n- 0.70 * justice_punitive : marqueur d'autorite fort car il insiste sur sanction et dissuasion.\\n- 0.70 * conservatisme : marqueur fort de continuite et stabilite.\\n- 0.30 * nationalisme : marqueur modere de souverainete, garde sous les axes d'autorite centraux.",
        "formula_raw_axis_explanation": "Le modele soustrait les blocs opposes. right_economic - left_economic donne la direction de x. authoritarian_social - libertarian_social donne la direction de y.",
        "formula_adjustments_explanation": "- productivisme - ecologie affine faiblement la lecture croissance contre contrainte ecologique.\\n- nationalisme - internationalisme affine faiblement la lecture souverainete contre ouverture internationale.\\n- revolution et reformisme servent a l'interpretation strategique detaillee, pas au positionnement x/y direct.",
        "formula_normalization_explanation": "Les scores bruts sont normalises avec tanh. Les profils marques se rapprochent des bords, mais le graphe reste lisible.",
    },
}


def translate(language: str, key: str) -> str:
    return UI_TEXT.get(language, UI_TEXT["en"]).get(key, UI_TEXT["en"].get(key, key))


def markdown_text(language: str, key: str) -> str:
    return translate(language, key).replace("\\n", "\n")
